name: optibot-mini-clone
jobs:
  - name: daily-scrape
    dockerfile_path: Dockerfile
    github:
      repo: tam130103/optibot-mini-clone
      branch: main
      deploy_on_push: true
    instance_size_slug: professional-xs
    instance_count: 1
    envs:
      - key: DEEPSEEK_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${DEEPSEEK_API_KEY}
    run_command: python main.py
    cron: "0 3 * * *"
